# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribebooks',
            old_name='book_id',
            new_name='bookID',
        ),
        migrations.RemoveField(
            model_name='subscribebooks',
            name='user_id',
        ),
        migrations.AddField(
            model_name='subscribebooks',
            name='userName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
