# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 07:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0002_auto_20170614_0713'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subscribeBooks',
            new_name='subscribedBooks',
        ),
    ]
