# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20170614_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscribeBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('book_id', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='subscribedBooks',
        ),
    ]
