# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-12 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('userID', models.BigIntegerField()),
                ('bookID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookID', models.BigIntegerField()),
                ('ISBN', models.CharField(max_length=20)),
                ('bookName', models.CharField(max_length=20)),
                ('bookType', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FavoredBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.BigIntegerField()),
                ('bookID', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.BigIntegerField(unique=True)),
                ('userName', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('mailBox', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubscribedBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.BigIntegerField()),
                ('bookID', models.BigIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='allBook',
        ),
        migrations.DeleteModel(
            name='favor',
        ),
        migrations.DeleteModel(
            name='message',
        ),
        migrations.DeleteModel(
            name='student_users',
        ),
        migrations.DeleteModel(
            name='subscribeBooks',
        ),
    ]
