# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170512_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookKind',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='cBussiness',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
