# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-14 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170514_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='userID',
        ),
    ]
