# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170514_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribedbook',
            name='userID',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='studentClass',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentuser',
            name='studentNumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscribedbook',
            name='classID',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
