# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-22 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='ISBN',
            new_name='bookKind1',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookKind',
            new_name='bookkind2',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='price',
            new_name='priceHalfYear',
        ),
        migrations.AddField(
            model_name='book',
            name='bookkind3',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='mailNumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pictureUrl',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pricePerMonth',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pricePerYear',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='standNumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
