# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-22 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170522_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookkind2',
            new_name='bookKind2',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookkind3',
            new_name='bookKind3',
        ),
    ]
