# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-22 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20170522_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='introduction',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
