# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-05-22 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_book_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bookName',
            field=models.CharField(max_length=40),
        ),
    ]
