# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-14 07:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_replytiezi_tiezi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribedbook',
            old_name='classID',
            new_name='userName',
        ),
    ]
