# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_booklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoredbook',
            name='userID',
        ),
        migrations.AddField(
            model_name='favoredbook',
            name='userName',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
